---
# tasks file for kubeways.fluentd-forwarder

- name: check fluentd logging is enabled
  set_fact:
    state: present
  when: fluentd_logging_syslog_enabled == true

- name: check fluentd logging is disabled
  set_fact:
    state: absent
  when: fluentd_logging_syslog_enabled == false

- name: deploy fluentd log forwarder on k8s
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', role_path + '/templates/fluentd-kubernetes-daemonset.yml.j2') }}"
  run_once: true
