---
# tasks file for kubeways.fluentd-forwarder

- name: check fluentd logging is enabled
  set_fact:
    state: present
  when: fluentd_logging_syslog_enabled == true

- name: check fluentd logging is disabled
  set_fact:
    state: absent
  when: fluentd_logging_syslog_enabled == false

- name: deploy service account for fluentd
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', role_path + '/templates/service-account.yaml.j2') }}"
  run_once: true

- name: deploy cluster role for fluentd
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', role_path + '/templates/cluster-role.yaml.j2') }}"
  run_once: true

- name: deploy cluster role binding for fluentd
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', role_path + '/templates/cluster-role-binding.yaml.j2') }}"
  run_once: true

- name: deploy fluentd log forwarder on k8s
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', role_path + '/templates/fluentd-kubernetes-daemonset.yaml.j2') }}"
  run_once: true
